spring:
  application:
    name: gulimall-coupon
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
        namespace: d6ca782e-0f97-4616-acbc-f90ec268ba92
#        group: dev

  config:
    import:
      - optional:nacos:datasource.yml?group=dev&refreshEnabled=true
      - optional:nacos:mybatis.yml?group=dev&refreshEnabled=true
      - optional:nacos:gulimall-coupon.yml?group=dev&refreshEnabled=true



server:
  port: 7000
