spring:
  application:
    name: gulimall-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
        namespace: 6180e8e6-9586-4aed-8a9f-ff1c2c3eaac1
#        group: dev

  config:
    import:
      - optional:nacos:gulimall-gateway.yml?group=dev&refreshEnabled=true



server:
  port: 88
